version: '3.4'

services:
  mongodb:
    image: mongo
    volumes:
      - db-mong:/data/db
    ports: 
      - 27017:27017
  djongo:
    restart: always
    image: djongo
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    links:
      - mongodb:mongodb
    environment:
      DEBUG: 'true'
  
volumes:
  db-mong:
