# Generated by Django 3.0.5 on 2021-09-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RightOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Right Owner's name", max_length=200)),
                ('role', models.CharField(help_text="Right Owner's role", max_length=200)),
                ('ipi', models.CharField(help_text='International identification number assigned to the right owner.', max_length=200)),
            ],
        ),
    ]
