# Generated by Django 3.0.5 on 2021-09-07 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('right_owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_society', models.CharField(help_text='Internal work id assigned by the society that provided the file.', max_length=100)),
                ('iswc', models.CharField(help_text='International Standard Musical Work Code', max_length=100)),
                ('right_owner', models.ManyToManyField(to='right_owners.RightOwner')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title', max_length=200)),
                ('type', models.CharField(blank=True, choices=[('original_title', 'ORIGINAL TITLE'), ('alternative_title_1', 'ALTERNATIVE TITLE 1'), ('alternative_title_2', 'ALTERNATIVE TITLE 2'), ('alternative_title_3', 'ALTERNATIVE TITLE 3'), ('alternative_title_4', 'ALTERNATIVE TITLE 4')], help_text='Title type', max_length=200, null=True)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='title_music', to='musics.Music')),
            ],
        ),
    ]
