# Generated by Django 3.0.5 on 2021-09-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(help_text='Internal work id assigned by the society that provided the file.', max_length=100)),
                ('iswc', models.CharField(help_text='International Standard Musical Work Code', max_length=100)),
                ('original_title', models.CharField(help_text='Original Title', max_length=200)),
                ('alternative_title_1', models.CharField(help_text='Alternative Title 1', max_length=200)),
                ('alternative_title_2', models.CharField(help_text='Alternative Title 2', max_length=200)),
                ('alternative_title_3', models.CharField(help_text='Alternative Title 3', max_length=200)),
            ],
        ),
    ]
