# Generated by Django 3.0.5 on 2021-09-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='alternative_title_1',
            field=models.CharField(blank=True, help_text='Alternative Title 1', max_length=200),
        ),
        migrations.AlterField(
            model_name='music',
            name='alternative_title_2',
            field=models.CharField(blank=True, help_text='Alternative Title 2', max_length=200),
        ),
        migrations.AlterField(
            model_name='music',
            name='alternative_title_3',
            field=models.CharField(blank=True, help_text='Alternative Title 3', max_length=200),
        ),
    ]
