# Generated by Django 3.0.5 on 2021-09-07 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_auto_20210907_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='title_music', to='musics.Music'),
        ),
    ]
