# Generated by Django 3.0.5 on 2021-09-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('right_owners', '0001_initial'),
        ('musics', '0003_auto_20210907_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='right_owner',
            field=models.ManyToManyField(to='right_owners.RightOwner'),
        ),
    ]
